name: syncfusion_flutter_calendar
description: The Flutter Calendar widget has nine built-in configurable views that provide basic functionalities for scheduling and representing appointments/events efficiently.
version: 29.1.40
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_calendar

environment:
  sdk: ^3.7.0-0

dependencies:
  flutter:
    sdk: flutter
  timezone: 0.10.0
  syncfusion_flutter_core: ^29.1.40
  syncfusion_flutter_datepicker: ^29.1.40
  intl: '>=0.18.1 <0.21.0'

flutter:
  assets:
    - packages/timezone/data/latest_all.tzf
