name: syncfusion_flutter_pdfviewer
description: Flutter PDF Viewer library is used to display a PDF document seamlessly and efficiently.
version: 29.1.40
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_pdfviewer

environment:
  sdk: ^3.7.0-0
  flutter: '>=1.20.0'

flutter:
  plugin:
    platforms:
      android:
        package: com.syncfusion.flutter.pdfviewer
        pluginClass: SyncfusionFlutterPdfViewerPlugin
      ios:
        pluginClass: SyncfusionFlutterPdfViewerPlugin
      web:
        default_package: syncfusion_pdfviewer_web
      macos:
        default_package: syncfusion_pdfviewer_macos
      windows:
        default_package: syncfusion_pdfviewer_windows

  assets:
    - assets/icons/dark/
    - assets/icons/light/
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.0
  web: ^1.0.0
  async: ^2.5.0
  http: ^1.0.0
  uuid: ^4.1.0
  device_info_plus: ^11.0.0
  intl: '>=0.18.1 <0.21.0'
  syncfusion_pdfviewer_platform_interface: ^29.1.40
  syncfusion_pdfviewer_web: ^29.1.40
  syncfusion_pdfviewer_macos: ^29.1.40
  syncfusion_pdfviewer_windows: ^29.1.40
  syncfusion_flutter_core: ^29.1.40
  syncfusion_flutter_pdf: ^29.1.40
  syncfusion_flutter_signaturepad: ^29.1.40
  url_launcher: ^6.1.0